In [1]:
print("NLP project started successfully")

NLP project started successfully

In [1]:
from datasets import load_dataset
import pandas as pd

print("Libraries imported successfully")

Libraries imported successfully

In [2]:
dataset = load_dataset("truehealth/medicationqa")
dataset

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/541 [00:00<?, ?B/s]

c:\Users\Serhat\Desktop\medicine-chatbot-nlp\medicine-chatbot-nlp\venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Serhat\.cache\huggingface\hub\datasets--truehealth--medicationqa. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

data/train-00000-of-00001-7427a10e891759(…):   0%|          | 0.00/215k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/690 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['Question', 'Focus (Drug)', 'Question Type', 'Answer', 'Section Title', 'URL'],
        num_rows: 690
    })
})

In [3]:
dataset.keys()

dict_keys(['train'])

In [5]:
dataset["train"][0]

{'Question': 'how does rivatigmine and otc sleep medicine interact',
 'Focus (Drug)': 'rivastigmine',
 'Question Type': 'Interaction',
 'Answer': "tell your doctor and pharmacist what prescription and nonprescription medications, vitamins, nutritional supplements, and herbal products you are taking or plan to take. Be sure to mention any of the following: antihistamines; aspirin and other nonsteroidal anti-inflammatory medications (NSAIDs) such as ibuprofen (Advil, Motrin) and naproxen (Aleve, Naprosyn); bethanechol (Duvoid, Urecholine); ipratropium (Atrovent, in Combivent, DuoNeb); and medications for Alzheimer's disease, glaucoma, irritable bowel disease, motion sickness, ulcers, or urinary problems. Your doctor may need to change the doses of your medications or monitor you carefully for side effects.",
 'Section Title': 'What special precautions should I follow?',
 'URL': 'https://medlineplus.gov/druginfo/meds/a602009.html'}

In [6]:
df = pd.DataFrame(dataset["train"])
df.head()

,Question,Focus (Drug),Question Type,Answer,Section Title,URL
0,how does rivatigmine and otc sleep medicine in...,rivastigmine,Interaction,tell your doctor and pharmacist what prescript...,What special precautions should I follow?,https://medlineplus.gov/druginfo/meds/a602009....
1,how does valium affect the brain,Valium,Action,Diazepam is a benzodiazepine that exerts anxio...,CLINICAL PHARMACOLOGY,https://dailymed.nlm.nih.gov/dailymed/drugInfo...
2,what is morphine,morphine,Information,Morphine is a pain medication of the opiate fa...,NaN,https://en.wikipedia.org/wiki/Morphine
3,what are the milligrams for oxycodone e,oxycodone ER,Dose,… 10 mg … 20 mg … 40 mg … 80 mg ...,HOW SUPPLIED,https://dailymed.nlm.nih.gov/dailymed/drugInfo...
4,81% aspirin contain resin and shellac in it. ?,aspirin 81 mg,Ingredient,Inactive Ingredients Ingredient Name,INGREDIENTS AND APPEARANCE,https://dailymed.nlm.nih.gov/dailymed/drugInfo...

In [7]:
df.columns

Index(['Question', 'Focus (Drug)', 'Question Type', 'Answer', 'Section Title',
       'URL'],
      dtype='str')

In [8]:
qa_df = df[["Question", "Answer"]]

qa_df.head()

,Question,Answer
0,how does rivatigmine and otc sleep medicine in...,tell your doctor and pharmacist what prescript...
1,how does valium affect the brain,Diazepam is a benzodiazepine that exerts anxio...
2,what is morphine,Morphine is a pain medication of the opiate fa...
3,what are the milligrams for oxycodone e,… 10 mg … 20 mg … 40 mg … 80 mg ...
4,81% aspirin contain resin and shellac in it. ?,Inactive Ingredients Ingredient Name

In [9]:
qa_df.shape

(690, 2)

In [10]:
qa_df.isnull().sum()

Question    0
Answer      1
dtype: int64

In [11]:
qa_df = qa_df.dropna()

qa_df.shape

(689, 2)

In [12]:
qa_df["answer_length"] = qa_df["Answer"].apply(len)

qa_df["answer_length"].describe()

count     689.000000
mean      395.528302
std       436.736589
min         4.000000
25%       117.000000
50%       256.000000
75%       521.000000
max      4322.000000
Name: answer_length, dtype: float64

In [13]:
for i in range(3):
    print("QUESTION:")
    print(qa_df.iloc[i]["Question"])
    
    print("\nANSWER:")
    print(qa_df.iloc[i]["Answer"])
    
    print("\n" + "="*80 + "\n")

QUESTION:
how does rivatigmine and otc sleep medicine interact

ANSWER:
tell your doctor and pharmacist what prescription and nonprescription medications, vitamins, nutritional supplements, and herbal products you are taking or plan to take. Be sure to mention any of the following: antihistamines; aspirin and other nonsteroidal anti-inflammatory medications (NSAIDs) such as ibuprofen (Advil, Motrin) and naproxen (Aleve, Naprosyn); bethanechol (Duvoid, Urecholine); ipratropium (Atrovent, in Combivent, DuoNeb); and medications for Alzheimer's disease, glaucoma, irritable bowel disease, motion sickness, ulcers, or urinary problems. Your doctor may need to change the doses of your medications or monitor you carefully for side effects.

================================================================================

QUESTION:
how does valium affect the brain

ANSWER:
Diazepam is a benzodiazepine that exerts anxiolytic, sedative, muscle-relaxant, anticonvulsant and amnestic effects. Most of these effects are thought to result from a facilitation of the action of gamma aminobutyric acid (GABA), an inhibitory neurotransmitter in the central nervous system.

================================================================================

QUESTION:
what is morphine

ANSWER:
Morphine is a pain medication of the opiate family which is found naturally in a number of plants and animals.[5][7] It acts directly on the central nervous system (CNS) to decrease the feeling of pain.

================================================================================

In [14]:
from sklearn.model_selection import train_test_split

train_df, temp_df = train_test_split(
    qa_df,
    test_size=0.2,
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    random_state=42
)

print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

Train: (551, 3)
Validation: (69, 3)
Test: (69, 3)

In [15]:
train_df.to_csv("../data/train.csv", index=False)
val_df.to_csv("../data/validation.csv", index=False)
test_df.to_csv("../data/test.csv", index=False)

print("Dataset files saved successfully.")

Dataset files saved successfully.

In [16]:
import os

print(os.listdir("../data"))

['.gitkeep', 'test.csv', 'train.csv', 'validation.csv']